Add IQM functionality to FwdFPGA.
daedaleanai/qemu pull request #18
Opened 2022-12-15 14:57 UTC by kirilldai

Added the IQM functionality such as Mapper for normalizing images, Debayer, and calculating of contrast and brightness. 
The logic of fwdfpga_xdma_engine_execute_descriptor was changed to detect a registers range and trigger specific functions such as accessing DRAM, triggering IQM, etc.

2022-12-15 18:14 UTC, jfrohnhofen requested changes
Hi Kirill, great job on your first PR. Some of the comments are specific to the IQM,some are more general about how to best structure the code to be able to integrate more components later. We can also discuss the feedback in person.

2022-12-15 18:14 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
Out of curiosity: Why do we divide by 8.0?

2022-12-15 18:14 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    double contrast1 = 0,
why use `double`s here instead of `uint64_t`s?

2022-12-15 18:14 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    if(engine->fpga_iqm->control & 1 && engine->fpga_iqm->status == 0)
We need to protect access to the IQM registers with a mutex to prevent different threads from setting / resetting the control register at the same time.

2022-12-15 18:14 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +        if (dram_offset != ~0ULL){
This approach for dispatching read / write requests to different memory ranges to different devices does not scale well to ~5 "blocks" / functions that we will want to implement. We should think about introducing some "block" abstraction. Maybe a struct that contains the base address and size, and two handler functions for read and write requests. Then this code could loop through the devices, find the one with the matching address range and dispatch the request.

2022-12-15 18:14 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +            memcpy(&pxl_value, engine->fpga_dram + input_offset + pixel_offset, 2);
@aburgm Do we need a mutex for the DRAM? The current code does not have one, does the `pcie_dma_read` function take care of that?

2022-12-16 08:41 UTC, aburgm commented on hw/misc/fwdfpga.c
> +    uint16_t debayer[1500][2048][4];
I'm a bit surprised you need a buffer for the entire image in the first place. The IQM does only pixel-wise operations, so it should be pretty easy to implement it without the dedicated buffer.

2022-12-16 08:42 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            memcpy(&pxl_value, engine->fpga_dram + input_offset + pixel_offset, 2);
and use uint16_t for pxl_value

2022-12-16 08:44 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            memcpy(&pxl_value, engine->fpga_dram + input_offset + pixel_offset, 2);
I would argue no, even if `pcie_dma_read` does not do any synchronization, because on the real hardware I doubt there is any synchronization either.

If I change the DRAM content that the IQM is currently operating on, I'll get unpredictable results and it's a programming error.

2022-12-16 08:48 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
So that the result fits in a 32-bit register even in the worst case (every pixel having maximum intensity). It's specified like this in the IQM ICD.

2022-12-16 08:52 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            if(pci_dma_read(engine->pdev, descriptor->srcAddress, (void *)engine->fpga_iqm + iqm_offset, descriptor->length) != MEMTX_OK) {
I have done reads and writes of multiple registers with a single DMA transaction of a multiple of 4 bytes before which seems to work fine (but I'm not doing it in the FwdFPGA Driver). Not sure about unaligned reads/writes for registers.

For reads/writes to the DRAM, there are no alignment requirements.

2022-12-16 08:55 UTC, aburgm commented on hw/misc/fwdfpga.c
> +    fwdfpga_xdma_engine_init(&fwdfpga->h2c_engines[0], FWD_FPGA_XDMA_ENGINE_DIRECTION_H2C, &fwdfpga->pdev, &fwdfpga->bar_mutex, fwdfpga->fpga_dram, &fwdfpga->fpga_iqm, &fwdfpga->bar.h2cChannel0, &fwd
The reason why I didn't do that already originally was that I wanted to avoid circular references, i.e. the FwdFPGA state containing the DMA engines and the DMA engines having a backward reference to the state.

Instead we could think about making a structure which contains the units, maybe together with some of the state used by the engine, and pass that instead.

But I agree it's fine as is for now.

2022-12-16 11:14 UTC, kirilldai commented on hw/misc/fwdfpga.c
> + * Length of FPGA's dedicated IQM.
Done

2022-12-16 12:00 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
Yes, according to IQM ICD. Should there be a comment in the code?

2022-12-16 12:01 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
It can't hurt

2022-12-16 12:02 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
Sure)

2022-12-16 15:00 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +const double IQM_ALPHA = 0.4400607;
Done

2022-12-16 15:07 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            check_status_iqm(engine);
pci_dma_read changes the state of Iqm, so as soon as it makes any changes in the Iqm structure, we're checking whether the control is b'1.

2022-12-16 15:48 UTC, aburgm commented on hw/misc/fwdfpga.c
> +            check_status_iqm(engine);
Honestly I'm not sure. I guess it could fail either in reading from the host memory or in writing to the card memory.

In practice it doesn't matter too much which error bit we set, as our XDMA driver will not differentiate between them. They are also not super-well documented:

![image](https://user-images.githubusercontent.com/5033091/208136099-327cb566-e1b8-4aca-b430-69a028f942bd.png)

2022-12-16 15:52 UTC, aburgm commented on hw/misc/fwdfpga.c
> +        qemu_thread_create(&engine->thread, "iqm", fwdfpga_iqm_thread, engine, QEMU_THREAD_DETACHED);
I still find this a bit problematic:

 - there is no synchronization with the detached thread, which prevents an orderly shutdown. If during qemu shutdown it destroys the FwdFPGA device, the detached thread might still be running in the background and now access invalid data.
 -  Since the `iqm->status` is only set within the launched thread there is a race condition in which it would be possible to start multiple IQM threads when repeatedly and very quickly writing "1" into the control register.

I encourage to instead start the thread at the FwdFPGA Device initialization and have it wait for incoming data, and then synchronize (join) it on destruction, in the same way the XDMA engine threads are handled.

2022-12-18 15:51 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    Iqm iqm_isntance;
Done

2022-12-18 15:52 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    iqm_isntance.debayer[0][0][0] = 0;
Got rid of a debayer buffer

2022-12-18 15:52 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    Iqm* fpga_iqm;
Understood. Changed

2022-12-18 15:53 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    Iqm fpga_iqm;
Done

2022-12-18 15:54 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    uint16_t debayer[1500][2048][4];
Got rid of a debayer buffer

2022-12-18 15:55 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +static void iqm_mapper(FwdFpgaXdmaEngine* engine){
Done

2022-12-18 15:56 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            memcpy(&pxl_value, engine->fpga_dram + input_offset + pixel_offset, 2);
Done

2022-12-18 15:56 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            pxl = 16 * (2.0 * sqrt(pxl) / IQM_ALPHA  - (2 * log(IQM_ALPHA * sqrt(pxl) + 1)) / (IQM_ALPHA * IQM_ALPHA));
Done

2022-12-18 15:56 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            memcpy(engine->fpga_dram + mapped_offset + pixel_offset, &pxl_value, 2);
Done

2022-12-18 15:57 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            memcpy(&engine->fpga_iqm->debayer[pixel_y / 2][pixel_x / 2][color_idx], engine->fpga_dram + mapped_offset + pixel_offset, 2);
Done

2022-12-18 15:57 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    iqm_debayer(engine);
Done

2022-12-18 15:57 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            bright_r += iqm->debayer[pixel_y][pixel_x][0] / 8.0;
Done

2022-12-18 15:57 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +            bright_rgb += mx_color / 8.0;
Done

2022-12-18 15:58 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +    double contrast1 = 0,
Done

2022-12-19 09:22 UTC, kirilldai commented on hw/misc/fwdfpga.c
> +typedef struct Iqm {
Done

2022-12-21 12:44 UTC, jfrohnhofen reviewed
This is looking fairly good. A few minor comments.

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +        iqm->fpga_dram = fpga_dram;
it is a bit weird that this is set here. can we set this up where the Iqm unit gets initialized?

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    iqm->status = 0;
there should be an additional flag (such as shutdown) that is set here and signals to the thread that it should terminate.

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    uint64_t addresses[] = {0, 0x2, 0x2000, 0x2002}; // Addresses of RGGB pixels in Bayer pattern
nit: how about calling this `bayer_offsets`?

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +        else{
nit: formatting

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +        else if (iqm_offset != ~0ULL){
nit: formatting

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +            if(pci_dma_read(engine->pdev, descriptor->srcAddress, engine->fpga_dram + dram_offset, descriptor->length) != MEMTX_OK) {
nit: formatting

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    if(iqm->control & 1 && iqm->status == 0){
nit: formatting

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    for(uint16_t pixel_y = 0; pixel_y < IQM_IMAGE_HEIGHT/2; pixel_y++){
nit: the code formatting is inconsistent in a few places. I left comments where I noticed, but might have missed some places. The coding style is described here: https://qemu-project.gitlab.io/qemu/devel/style.html#qemu-coding-style
Violation that I found are:
1. missing spaces between `if` / `for` and the following `(` or between `)` and `{` at the beginning of blocks
2. `else` should be on the same line as the `}` of the previous block

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    iqm->bright_r = bright_r / 8.0;
since these are all integer divisions, the divisors should be integers as well. Aka remove the `.0` after the constants.

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    contrast1 /= 4.0,
same

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    contrast2 /= 16.0;
same

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +    iqm->status = 1;
nit: It is a bit asymmetric that `execute_iqm` sets the busy status bit, but the bit is cleared in `fwdfpga_iqm_thread`. I would suggest setting the status in `fwdfpga_iqm_thread` as well (and possibly even while the mutex is locked).

2022-12-21 12:44 UTC, jfrohnhofen commented on hw/misc/fwdfpga.c
> +
you should check for a `shutdown` flag here that is set by the uninit function and exit the loop (and thus the thread) when it is set.

2022-12-28 08:30 UTC, aburgm approved these changes
Looks good to me overall, I only have two minor comments left

2022-12-28 08:30 UTC, aburgm commented on hw/misc/fwdfpga.c
> +                mx_color = fmax(mx_color, pixel_val);
A bit strange/wasteful to use floating points just to get the maximum, consider replacing with `if (pixel_val > mx_color) mx_color = pixel_val;`

2022-12-28 08:30 UTC, aburgm commented on hw/misc/fwdfpga.c
> +    fwdfpga->iqm.fpga_dram = fwdfpga->fpga_dram;
It would be a bit cleaner if you assign this inside `fwdfpga_iqm_init` and pass it as a second argument to it

2023-01-05 08:04 UTC, jfrohnhofen approved these changes
LGTM

2023-01-05 15:15 UTC, merged