Split IQM, IPP and FwdFPGA
daedaleanai/qemu pull request #25
Opened 2023-01-25 15:41 UTC by kirilldai

2023-01-25 15:52 UTC, kirilldai commented
I'm unsure if I separated the structures in the .c and .h files correctly, so I look forward to your comments.

2023-01-26 10:27 UTC, aburgm requested changes
Thanks, this is exactly what I had in mind. I think it gives a lot more structure to the code.

You can optimize a bit what's defined in the `.h` and the `.c` files, see my inline comments.

2023-01-26 10:27 UTC, aburgm commented on hw/misc/fwdfpga/iqm.h
> +typedef struct Iqm {
Rename to FwdFpgaIqm?

2023-01-26 10:27 UTC, aburgm commented on hw/misc/fwdfpga/iqm.h
> +void* fwdfpga_iqm_thread(void* context);
In the header files, ideally you only expose structs and function declarations that are needed by other `.c` files. For example, `fwdfpga_iqm_init()`, `fwdfpga_iqm_uninit()` and `check_status_iqm()` are needed by `fwdfpga.c`, but `fwdfpga_iqm_thread()` is internal to the IQM module, it's only used by the init() function. So it should be moved to the `iqm.c` file, so that nobody else can (accidentally or not) call it.

Please also check ipp.c and fwdfpga.c (for example some of the Xdma structures can probably be private) for these.

2023-01-26 10:27 UTC, aburgm commented on hw/misc/fwdfpga/iqm.h
> +void check_status_iqm(void *device);
In C, due to the lack of namespaces, it is good practice to use common prefixes. For example, everything that's in the `fwdfpga/iqm.h` file should be prefixed with `fwdfpga_iqm_XXX` (or FwdFpgaIqm if it's a struct).

2023-01-27 14:01 UTC, kirilldai commented on hw/misc/fwdfpga/iqm.h
> +typedef struct Iqm {
Done

2023-01-27 14:03 UTC, kirilldai commented on hw/misc/fwdfpga/iqm.h
> +void* fwdfpga_iqm_thread(void* context);
Changed. For fwdfpga.h I moved all structures to fwdfpga.c because as I understand none of them will be called from outside.

2023-01-27 14:03 UTC, kirilldai commented on hw/misc/fwdfpga/iqm.h
> +void check_status_iqm(void *device);
Done

2023-01-30 08:47 UTC, aburgm approved these changes
Looks good to me, thanks!

2023-01-30 09:20 UTC, merged