Add DTA to FwdFpga
daedaleanai/qemu pull request #26
Opened 2023-01-30 10:28 UTC by kirilldai

2023-01-30 10:56 UTC, kirilldai commented
I edited the implementation according to comments from the previous PR

2023-01-31 09:19 UTC, aburgm requested changes

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +        qemu_mutex_unlock(dta->mutex);
I suggest to load all the variables you need from the dta struct here, before unlocking the mutex, and then avoid mutex locks further down in this function.

Otherwise you can have race conditions where for example you load `dta->load_len`, then somebody changes `load_len` and `load_baseaddr`, and then you load `dta->load_baseaddr`. Now you have an inconsistent pair of `load_len` and `load_baseaddr`.

Ideally you also pass these read values to `fwdfpga_dta_process_load_instruction()` instead of reading them from the dta struct there again, for the same reason. The same applies to the execute and store modules as well.

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +        qemu_mutex_lock(dta->mutex);
extra unlock->lock cycle here not needed

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +        qemu_cond_wait(dta->load.cv, dta->load.mutex);
this is a bit dangerous. A condition variable should only be used together with a condition that you can check, for example a flag whether the LOAD module has been started or not. The reason is that condition variables can be signalled "spuriously" (more info for example [here](https://en.wikipedia.org/wiki/Spurious_wakeup)). Here is an example of a typical usage:

In the waiting thread:
```
while(1) {
    qemu_cond_wait(dta->load.cv, dta->load.mutex);
    if (dta->load.shutdown) {
        break;
    }
    if (!dta->load.run_requested) {
        continue;
    }
    qemu_mutex_unlock();
    ...
    qemu_mutex_lock();
    dta->load.run_requested = 0;
}
```

And in the calling thread:
```
qemu_mutex_lock();
dta->load.run_requested = 1;
qemu_cond_signal(dta->load.cv);
qemu_mutex_unlock();
```

The same applies to the other DTA modules and the top-level `fwdfpga_dta_thread()` function.

I also just went back and checked the IQM and the IPP, and I think they have the same problem. For example, in `fwdfpga_ipp_thread()`, it should check `ipp->control` before starting the work, and similar for IQM.

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +        info_report("Dta successfully finished");
you want to leave this in?

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +    dta->load.name = (char*)"load";
declare the name as `const char*` and you won't need the cast

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +    dta->thread = g_malloc0(sizeof(QemuThread));
you probably don't need to heap-allocate these anymore?

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +    dta_module->thread = g_malloc0(sizeof(QemuThread));
same here?

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +    qemu_mutex_destroy(dta->mutex);
If you keep the g_malloc, you need to g_free them here

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.c
> +    qemu_mutex_destroy(dta_module->mutex);
If you keep the g_malloc, you need to g_free them here

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/fwdfpga.c
> +    fwdfpga_dta_module_uninit(&fwdfpga->dta->store, fwdfpga->dta);
It's probably safer to uninit the modules before uninit'ing the DTA itself. For example, the DTA uninit destroys the semaphores that the module threads might still try to access.

2023-01-31 09:19 UTC, aburgm commented on hw/misc/fwdfpga/dta.h
> +    sem_t module_finished_flag;
It's a bit strange/inconsistent to use pthread semaphores when the other threading primitives used are from qemu. Can you use `QemuSemaphore` and `qemu_sem_init()` etc. instead?

2023-01-31 11:19 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +        sram_index = instr->sram_base_index;
Done

2023-01-31 11:22 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +static void fwdfpga_dta_process_load_instruction(TransferInstruction *instr, FwdFpgaDta *dta, int instr_idx) {
Removed

2023-01-31 11:23 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +static void fwdfpga_dta_process_store_instruction(TransferInstruction *instr, FwdFpgaDta *dta, int instr_idx) {
Removed

2023-01-31 11:26 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    qemu_mutex_destroy(dta_module->mutex);
Removed g_malloc

2023-01-31 11:26 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    dta_module->thread = g_malloc0(sizeof(QemuThread));
Changed

2023-01-31 11:27 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    qemu_mutex_destroy(dta->mutex);
Removed g_malloc

2023-01-31 11:27 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    dta->thread = g_malloc0(sizeof(QemuThread));
Yes. Removed

2023-01-31 11:30 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    dta->load.name = (char*)"load";
Done

2023-01-31 11:36 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +        info_report("Dta successfully finished");
No

2023-01-31 11:36 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +        qemu_mutex_lock(dta->mutex);
Changed

2023-01-31 11:38 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +    qemu_mutex_unlock(dta->mutex);
Right, changed

2023-01-31 12:01 UTC, kirilldai commented on hw/misc/fwdfpga/dta.h
> +    sem_t module_finished_flag;
Changed

2023-01-31 12:24 UTC, kirilldai commented on hw/misc/fwdfpga/fwdfpga.c
> +    fwdfpga_dta_module_init(&fwdfpga->dta->store, fwdfpga->dta);
Moved

2023-01-31 15:45 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +            memcpy(dta->fpga_dram + dta->vars_baseaddr + dram_addr, dta->val_sram_bank + sram_addr, FWDFPGA_DTA_DRAM_WORD_SIZE);
Changed

2023-01-31 17:09 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +                        if (uop.opcode >= 5 && uop.opcode <= 7) {
Done

2023-02-01 09:56 UTC, aburgm approved these changes
Looks good to me! Thanks for the changes :)

2023-02-01 12:25 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> + * Offset of IPP in FPGA address space.
Done

2023-02-01 12:25 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> + * Size of IPP register bank.
Done

2023-02-01 12:25 UTC, kirilldai commented on hw/misc/fwdfpga/dta.c
> +static void executeTail(int64_t *acc_tensor, int64_t shr_imm, int64_t max_imm) {
Done

2023-02-03 09:16 UTC, merged